# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-06-06 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name=b'Subject')),
                ('contact_email', models.CharField(max_length=100, verbose_name=b'Mail To')),
                ('content', models.CharField(max_length=400, verbose_name=b'Content')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name=b'First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name=b'Last Name')),
                ('username', models.CharField(max_length=100, verbose_name=b'User Name')),
                ('password', models.CharField(max_length=100, verbose_name=b'Password')),
                ('confirm_password', models.CharField(max_length=100, verbose_name=b'Confirm Password')),
                ('email', models.CharField(max_length=100, verbose_name=b'Email')),
            ],
        ),
    ]
