# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-06-07 09:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_insert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insert',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='insert',
            name='last_name',
        ),
        migrations.AddField(
            model_name='insert',
            name='email_name',
            field=models.CharField(default=datetime.datetime(2016, 6, 7, 9, 47, 41, 205545, tzinfo=utc), max_length=100, verbose_name=b'Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insert',
            name='password',
            field=models.CharField(default=datetime.datetime(2016, 6, 7, 9, 47, 46, 500626, tzinfo=utc), max_length=100, verbose_name=b'Password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insert',
            name='user_name',
            field=models.CharField(default=datetime.datetime(2016, 6, 7, 9, 47, 52, 4621, tzinfo=utc), max_length=80, verbose_name=b'User name'),
            preserve_default=False,
        ),
    ]
