# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-06-07 12:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20160607_0947'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
        migrations.AddField(
            model_name='insert',
            name='contact_email',
            field=models.CharField(default=datetime.datetime(2016, 6, 7, 12, 33, 37, 430944, tzinfo=utc), max_length=100, verbose_name=b'Mail To'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insert',
            name='content',
            field=models.CharField(default=datetime.datetime(2016, 6, 7, 12, 33, 40, 430678, tzinfo=utc), max_length=400, verbose_name=b'Content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insert',
            name='subject',
            field=models.CharField(default=datetime.datetime(2016, 6, 7, 12, 33, 44, 646404, tzinfo=utc), max_length=200, verbose_name=b'Subject'),
            preserve_default=False,
        ),
    ]
