# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-06-07 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20160607_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80, verbose_name=b'First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name=b'Last Name')),
                ('username', models.CharField(max_length=100, verbose_name=b'User Name')),
                ('password', models.CharField(max_length=100, verbose_name=b'Password')),
                ('confirm_password', models.CharField(max_length=100, verbose_name=b'Confirm Password')),
                ('email', models.CharField(max_length=100, verbose_name=b'Email')),
            ],
        ),
    ]
