# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-06-28 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insert',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='insert',
            name='content',
        ),
        migrations.RemoveField(
            model_name='insert',
            name='subject',
        ),
    ]
